base/urls.py
from django.conf.urls import patterns, url

from base import views

urlpatterns = patterns('',
                       url (r'^change_theme$', views.change_theme, name='change_theme'),
                       url (r'^update_revision$', views.update_revision, name='update_revision'),
                       )

forum/urls.py
from django.conf.urls import patterns, url

from forum import views

urlpatterns = patterns('',
                       #url (r'^$', views.MessageList.as_view (), name='list_view'),
                       url (r'^$', views.message_list_view, name='list_view'),
                       url (r'^add_post$', views.add_post, name='add_post'),
                       url (r'^update$', views.update_posts, name='update_posts'),
                       url (r'^toggle_sounds$', views.toggle_sounds, name='toggle_sounds'),
                       )

makalgo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'makalgo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^forum/', include('forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^user_activity/', include('user_activity.urls', namespace='user_activity')),
    url(r'', include('forum.urls', namespace='forum')),
)

forum/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Messages(models.Model):
    text = models.TextField(max_length=65536)
    date = models.DateTimeField('publishing date', default=timezone.now())
    author = models.CharField(max_length=30)

    def __unicode__(self):
        return u'%s' % self.text


class Visibility(models.Model):
    author = models.ForeignKey('Author', null=True, blank=True)
    begin = models.DateTimeField(default=timezone.now())
    end = models.DateTimeField(default=timezone.now())
    ip1 = models.GenericIPAddressField(default='0.0.0.0')
    ip2 = models.GenericIPAddressField(default='0.0.0.0')

    def __unicode__(self):
        return u': %s - %s' % (self.begin, self.end)


class Author(models.Model):
    username = models.CharField(max_length=30, unique=True)
    last_seen = models.ForeignKey(Visibility, related_name='+', null=True)

    def __unicode__(self):
        return u'%s' % self.username

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.templatetags.static import static
from django.views import generic
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from base.decorators import authentication_check, post_check
import json
from django.utils.formats import date_format
from django.utils.timezone import localtime
from django.core.context_processors import csrf
from django.template.defaultfilters import linebreaksbr
from datetime import timedelta
from django.core.exceptions import ObjectDoesNotExist

from forum.models import Messages
from forum.models import Author, Visibility
from base.models import Config


def get_author(request):
    return request.COOKIES.get('author', 'Anonymous')


def get_message_sound(request):
    if int(request.COOKIES.get('play_sounds', '1')):
        return static('forum/media/message_sounds/default.wav')
    return None


@authentication_check
def message_list_view(request, error_message=None):
    author = get_author(request)
    data = {
        'messages': Messages.objects.order_by('-date')[:50],
        'author': author,
        'error_message': error_message,
        'message_sound': get_message_sound(request),
    }
    response = render(request, 'forum/message_list.html', data)
    return response


@authentication_check
def add_post(request):

    if 'post_content' in request.POST and 'post_author' in request.POST:
        if 'change_nick' not in request.POST:
            new_message = Messages(author=request.POST['post_author'], text=request.POST['post_content'], date=timezone.now())
            new_message.save()

        response = HttpResponseRedirect(reverse('forum:list_view'))
        response.set_cookie('author', request.POST.get('post_author', 'Anonymous').encode('utf-8'), max_age=365*24*60*60)

        return response

    return message_list_view(request, 'something gone wrong')


def user_list(admin=False):
    users = Author.objects.filter(last_seen__end__gte=timezone.now()).order_by('username')
    users = {'%d' % k.id: k.username for k in users if k.username[-1] != '_' or admin}
    return users


@post_check
@authentication_check
def update_posts(request):
    refresh = False
    last = int(request.POST.get('last', 0))
    username = get_author(request)

    (author, created) = Author.objects.get_or_create(username=username)

    if created or author.last_seen.end < timezone.now():
        vis = Visibility(begin=timezone.now(), end=timezone.now() + timedelta(seconds=30), author=author)
        vis.save()
        author.last_seen = vis
        author.save()
    else:
        author.last_seen.end = timezone.now() + timedelta(seconds=30)
        author.last_seen.save()

    try:
        last_message = Messages.objects.filter(id__lte=last).order_by('-date')[0]
        last_date = last_message.date
        #last = last_message.id
        messages = Messages.objects.filter(date__gt=last_date).order_by('date')
        last = messages.last().id
        messages = [{'author': k.author, 'text': linebreaksbr(k.text), 'date': date_format(localtime(k.date), 'DATETIME_FORMAT')} for k in messages]
    except (IndexError, AttributeError):
        messages = []
        pass

    try:
        revision = Config.objects.get(key='revision').value
    except ObjectDoesNotExist:
        revision = '0'

    j = json.dumps({'last': last, 'messages': messages, 'users': user_list(request.user.is_superuser), 'refresh': refresh, 'revision': revision})
    return HttpResponse(j, mimetype='application/json')


def get_sound_icon(context):
    return '<div class="sound_{}"></div>'.format(
        'on' if context['request'].COOKIES.get('play_sounds', '1') == '1' else 'off'
    )


def toggle_sounds(request):
    response = HttpResponseRedirect(request.GET.get('next', '/'))
    value = int(request.COOKIES.get('play_sounds', '1'))
    value = 1 - value
    response.set_cookie('play_sounds', str(value), max_age=365*24*60*60)
    return response

forum/templates/forum/message_list.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load custom_css %}
{% load config_loader %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% css_dir 'forum/css/forum.css' %}">
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var last = {{ messages.0.id }}
        var update_url = '{% url 'forum:update_posts' %}'
        var revision = {% site_revision %}
        {% autoescape off %}
            var message_sound_path = '{{ message_sound }}'
        {% endautoescape %}
    </script>
    <script type="text/javascript" src="{% static 'forum/js/refresh_scripts.js' %}"></script>
{% endblock %}

{% block title %}Forum{% endblock %}

{% block content %}
    <ul id="update_alert"></ul>
    <div class="inner_window">
        <h1 class="title">Makalgo-2.0</h1>
    </div>

    <div class="inner_window">
        <form method="post" action="{% url 'forum:add_post' %}">
            {% csrf_token %}
            <label for="post_author">Author: </label>
            <input type="text" name="post_author" id="post_author" value="{{ author }}">
            <input type="submit" value="Change Nick" name="change_nick">
            <br>
            <label for="post_content">Text:</label>
            <br>
            <textarea name="post_content" id="post_content"></textarea>
            <br>
            <input type="submit">
        </form>
    </div>

    <ul id="user_list" class="hidden"><li class="user_list_title">Users</li></ul>

    <div class="inner_window">
        <ul id="post_list" class="post_list">
            {% for message in messages %}
                <li class="post {% cycle 'row1' 'row2' as rowcolor %}">
                    <div class="post_header">
                        <div class="post_date">{{ message.date }}</div>
                        <div class="post_author">{{ message.author }}</div>
                    </div>
                    <div class="post_text">
                        {{ message.text|safe|linebreaksbr }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}