accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
                       url(r'^login$', views.login_form, name='login'),
                       url(r'^authenticate$', views.auth, name='authenticate'),
                       url(r'^logout$', views.deauth, name='logout'),
                       )

base/urls.py
from django.conf.urls import patterns, url

from base import views

urlpatterns = patterns('',
                       url (r'^change_theme$', views.change_theme, name='change_theme'),
                       url (r'^update_revision$', views.update_revision, name='update_revision'),
                       )

makalgo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'makalgo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^forum/', include('forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^user_activity/', include('user_activity.urls', namespace='user_activity')),
    url(r'', include('forum.urls', namespace='forum')),
)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.


def login_form(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(request.GET.get('next', '/'))
    return render(request, 'accounts/login.html', {'next': request.GET.get('next', '/')})


def auth(request):
    if 'password' in request.POST:
        user = authenticate(username='makalgo_user', password=request.POST['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.POST.get('next', '/'))
    return render(request, 'accounts/login.html', {'next': request.POST.get('next', '/')})


def deauth(request):
    logout(request)
    return HttpResponseRedirect(request.GET.get('next', '/'))

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}">
{% endblock %}

{% block content %}
<div class="login_form">
    <h3 class="login">Login:</h3>
    <form action="{% url 'accounts:authenticate' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <label for="password">Password:</label><input type="password" id="password" name="password">
        <br>
        <input type="submit">
    </form>
</div>
{% endblock %}